Repository Badger-Finance/v2-ui, pull requests merged in 2022-04, with the labels that each got.

#1986 feat: vault filters v2
  .env
  public/assets/icons/vault-sort-arrow-v2.svg
  src/components-v2/VaultSearchControls/BoostedVaultsControl.tsx
  src/components-v2/VaultSearchControls/MobileFiltersButton.tsx
  src/components-v2/VaultSearchControls/OnlyDepositsControl.tsx
  src/components-v2/VaultSearchControls/PortfolioDustControl.tsx
  src/components-v2/VaultSearchControls/VaultFiltersDialogV2.tsx
  src/components-v2/VaultSearchControls/VaultSearchBar.tsx
  src/components-v2/VaultSearchControls/VaultSearchInputsRow.tsx
  src/components-v2/VaultSearchControls/VaultStatusSelector.tsx
  src/components-v2/VaultSearchControls/VaultsAprControl.tsx
  src/components-v2/VaultSearchControls/VaultsCurrencyControl.tsx
  src/components-v2/VaultSearchControls/VaultsPlatformSelector.tsx
  src/components-v2/VaultSearchControls/VaultsRewardsSelector.tsx
  src/components-v2/VaultSearchControls/VaultsSearchControls.tsx
  src/components-v2/VaultSearchControls/index.tsx
  src/components-v2/VaultSearchControls/types.ts
  src/components-v2/common/VaultListFiltersWidget.tsx
  src/components-v2/landing/CurrencyPicker.tsx
  src/components-v2/landing/VaultListHeader.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/config/environment.ts
  src/config/ui/dark.tsx
  src/mobx/model/ui/vaults-filters.ts
  src/mobx/stores/VaultStore.ts
  src/pages/Landing.tsx
  src/tests/CurrencyPicker.test.tsx
  src/tests/__snapshots__/CurrencyPicker.test.tsx.snap
  src/tests/vaults/VaultFiltersDialogV2.test.tsx
  src/tests/vaults/VaultsSearchControl.test.tsx
  src/tests/vaults/__snapshots__/VaultFiltersDialogV2.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultsSearchControl.test.tsx.snap
Labels: enhancement

#1994 chore: add usdc-dei
  src/config/deployments/ftm.json
  src/config/system/strategies.ts
  src/mobx/model/network/ftm.network.ts
Labels: enhancement

#1995 fix: linter post fix
  src/config/system/strategies.ts
Labels: bug

#1997 chore: add dei svg
  public/assets/icons/dei.svg
Labels: enhancement

#1998 staging: oxd vaults, ux enhancements + locking store fix
  .env
  public/assets/icons/bveoxd.svg
  public/assets/icons/dei.svg
  public/assets/icons/vault-sort-arrow-v2.svg
  src/components-v2/VaultSearchControls/BoostedVaultsControl.tsx
  src/components-v2/VaultSearchControls/MobileFiltersButton.tsx
  src/components-v2/VaultSearchControls/OnlyDepositsControl.tsx
  src/components-v2/VaultSearchControls/PortfolioDustControl.tsx
  src/components-v2/VaultSearchControls/VaultFiltersDialogV2.tsx
  src/components-v2/VaultSearchControls/VaultSearchBar.tsx
  src/components-v2/VaultSearchControls/VaultSearchInputsRow.tsx
  src/components-v2/VaultSearchControls/VaultStatusSelector.tsx
  src/components-v2/VaultSearchControls/VaultsAprControl.tsx
  src/components-v2/VaultSearchControls/VaultsCurrencyControl.tsx
  src/components-v2/VaultSearchControls/VaultsPlatformSelector.tsx
  src/components-v2/VaultSearchControls/VaultsRewardsSelector.tsx
  src/components-v2/VaultSearchControls/VaultsSearchControls.tsx
  src/components-v2/VaultSearchControls/index.tsx
  src/components-v2/VaultSearchControls/types.ts
  src/components-v2/common/VaultListFiltersWidget.tsx
  src/components-v2/landing/CurrencyPicker.tsx
  src/components-v2/landing/VaultListHeader.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components/Boost/Optimizer.tsx
  src/config/deployments/ftm.json
  src/config/environment.ts
  src/config/system/strategies.ts
  src/config/ui/dark.tsx
  src/config/wallets.ts
  src/mobx/model/network/ftm.network.ts
  src/mobx/model/ui/vaults-filters.ts
  src/mobx/stores/LockedDepositsStore.ts
  src/mobx/stores/VaultStore.ts
  src/pages/Landing.tsx
  src/tests/CurrencyPicker.test.tsx
  src/tests/__snapshots__/CurrencyPicker.test.tsx.snap
  src/tests/boost-optimizer/__snapshots__/Optimizer.test.tsx.snap
  src/tests/vaults/VaultFiltersDialogV2.test.tsx
  src/tests/vaults/VaultsSearchControl.test.tsx
  src/tests/vaults/__snapshots__/VaultFiltersDialogV2.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultsSearchControl.test.tsx.snap
Labels: enhancement

#1999 release: oxd vaults, ux enhancements
  .env
  public/assets/icons/bveoxd.svg
  public/assets/icons/dei.svg
  public/assets/icons/vault-sort-arrow-v2.svg
  src/components-v2/VaultSearchControls/BoostedVaultsControl.tsx
  src/components-v2/VaultSearchControls/MobileFiltersButton.tsx
  src/components-v2/VaultSearchControls/OnlyDepositsControl.tsx
  src/components-v2/VaultSearchControls/PortfolioDustControl.tsx
  src/components-v2/VaultSearchControls/VaultFiltersDialogV2.tsx
  src/components-v2/VaultSearchControls/VaultSearchBar.tsx
  src/components-v2/VaultSearchControls/VaultSearchInputsRow.tsx
  src/components-v2/VaultSearchControls/VaultStatusSelector.tsx
  src/components-v2/VaultSearchControls/VaultsAprControl.tsx
  src/components-v2/VaultSearchControls/VaultsCurrencyControl.tsx
  src/components-v2/VaultSearchControls/VaultsPlatformSelector.tsx
  src/components-v2/VaultSearchControls/VaultsRewardsSelector.tsx
  src/components-v2/VaultSearchControls/VaultsSearchControls.tsx
  src/components-v2/VaultSearchControls/index.tsx
  src/components-v2/VaultSearchControls/types.ts
  src/components-v2/common/VaultListFiltersWidget.tsx
  src/components-v2/landing/CurrencyPicker.tsx
  src/components-v2/landing/VaultListHeader.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components/Boost/Optimizer.tsx
  src/config/deployments/ftm.json
  src/config/environment.ts
  src/config/system/strategies.ts
  src/config/ui/dark.tsx
  src/config/wallets.ts
  src/mobx/model/network/ftm.network.ts
  src/mobx/model/ui/vaults-filters.ts
  src/mobx/stores/LockedDepositsStore.ts
  src/mobx/stores/VaultStore.ts
  src/pages/Landing.tsx
  src/tests/CurrencyPicker.test.tsx
  src/tests/__snapshots__/CurrencyPicker.test.tsx.snap
  src/tests/boost-optimizer/__snapshots__/Optimizer.test.tsx.snap
  src/tests/vaults/VaultFiltersDialogV2.test.tsx
  src/tests/vaults/VaultsSearchControl.test.tsx
  src/tests/vaults/__snapshots__/VaultFiltersDialogV2.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultsSearchControl.test.tsx.snap
Labels: enhancement, on hold

#2016 docs: 2.16.0
  changelog.md
  src/components-v2/navbar/NavbarInfoRow.tsx
  src/components-v2/sidebar/index.tsx
  src/config/constants.ts
Labels: enhancement

#2017 staging: 2.16.0
  changelog.md
  src/components-v2/NetworkURLManager/index.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/VaultDeprecationWarning/index.tsx
  src/components-v2/common/NetworkWidget.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
  src/components-v2/navbar/NavbarInfoRow.tsx
  src/components-v2/navbar/NavbarTabs.tsx
  src/components-v2/network-selector/NetworkOption.tsx
  src/components-v2/sidebar/index.tsx
  src/components-v2/vault-detail/MainContent.tsx
  src/components-v2/vault-detail/TopContent.tsx
  src/components-v2/vault-detail/holdings/HoldingItem.tsx
  src/components-v2/vault-detail/holdings/Holdings.tsx
  src/config/constants.ts
  src/config/routes.tsx
  src/hooks/usePrevious.ts
  src/index.tsx
  src/mobx/stores/NetworkStore.ts
  src/mobx/stores/OnboardStore.ts
  src/mobx/stores/UserStore.ts
  src/mobx/stores/VaultStore.ts
  src/tests/sett-details/Holdings.test.tsx
  src/tests/sett-details/__snapshots__/Holdings.test.tsx.snap
  src/tests/utils/samples.ts
Labels: enhancement

#2019 release: 2.16.0
  changelog.md
  src/components-v2/NetworkURLManager/index.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/VaultDeprecationWarning/index.tsx
  src/components-v2/common/NetworkWidget.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
  src/components-v2/navbar/NavbarInfoRow.tsx
  src/components-v2/navbar/NavbarTabs.tsx
  src/components-v2/network-selector/NetworkOption.tsx
  src/components-v2/sidebar/index.tsx
  src/components-v2/vault-detail/MainContent.tsx
  src/components-v2/vault-detail/TopContent.tsx
  src/components-v2/vault-detail/holdings/HoldingItem.tsx
  src/components-v2/vault-detail/holdings/Holdings.tsx
  src/config/constants.ts
  src/config/routes.tsx
  src/hooks/usePrevious.ts
  src/index.tsx
  src/mobx/stores/NetworkStore.ts
  src/mobx/stores/OnboardStore.ts
  src/mobx/stores/UserStore.ts
  src/mobx/stores/VaultStore.ts
  src/tests/sett-details/Holdings.test.tsx
  src/tests/sett-details/__snapshots__/Holdings.test.tsx.snap
  src/tests/utils/samples.ts
Labels: enhancement

#2028 staging: img fix + redirect fix
  src/components-library/NotificationSnackbar.tsx
  src/components-v2/vault-detail/VaultDetail.tsx
  src/mobx/stores/UserStore.ts
  src/mobx/stores/VaultStore.ts
  src/tests/components-library/__snapshots__/NotificationsSnackbar.test.tsx.snap
Labels: enhancement

#2029 release: img+ redirect fix
  src/components-library/NotificationSnackbar.tsx
  src/components-v2/vault-detail/VaultDetail.tsx
  src/mobx/stores/UserStore.ts
  src/mobx/stores/VaultStore.ts
  src/tests/components-library/__snapshots__/NotificationsSnackbar.test.tsx.snap
Labels: enhancement

#2034 feat(ui-library): add switches theme config
  src/config/ui/dark.tsx
  src/stories/Switch.stories.tsx
  src/stories/SwitchWithLabel.stories.tsx
Labels: enhancement

#2040 chore: update tabs + remove digg header
  src/components-v2/navbar/NavbarTabs.tsx
  src/components/Digg/index.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
Labels: enhancement

#2042 chore: add dig marging
  src/components/Digg/index.tsx
Labels: enhancement

#2041 staging: ui library + minor ux improvements
  src/components-v2/navbar/NavbarTabs.tsx
  src/components/Digg/index.tsx
  src/config/ui/dark.tsx
  src/stories/Button.stories.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
Labels: enhancement
