Repository Badger-Finance/v2-ui, pull requests merged in 2022-08, with the labels that each got.

#2248 chore: utilize new period apr
  package.json
  src/components-v2/VaultApyInformation/index.tsx
  src/config/deployments/mainnet.json
  src/hooks/useVaultInformation.ts
  src/mobx/model/network/eth.network.ts
  src/tests/utils/samples.ts
  src/tests/vaults/VaultItemApr.test.tsx
  yarn.lock
Labels: enhancement

#2252 staging: new vault apr + patch fixes
  package.json
  src/components-v2/InfluenceVault/InfluenceVaultUtil.tsx
  src/components-v2/VaultApyBreakdownItem/index.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/landing/VaultItemApr.tsx
  src/components-v2/landing/VaultLogo.tsx
  src/components-v2/network-selector/NetworkOption.tsx
  src/config/deployments/mainnet.json
  src/hooks/useVaultInformation.ts
  src/mobx/model/network/eth.network.ts
  src/setupTests.js
  src/tests/NetworkGasWidget.test.tsx
  src/tests/unit/componentHelpers.test.ts
  src/tests/unit/token/token-balance.test.ts
  src/tests/utils/samples.ts
  src/tests/vaults/VaultItemApr.test.tsx
  src/tests/vaults/__snapshots__/VaultItemApr.test.tsx.snap
  src/utils/componentHelpers.ts
  src/utils/enums/boosted-rewards.enum.ts
  yarn.lock
Labels: enhancement

#2257 feat: utilize v3 charting library
  package.json
  src/components-v2/InfluenceVault/InfluenceVaultInfoPanel.tsx
  src/components-v2/vault-detail/charts/BoostChart.tsx
  src/components-v2/vault-detail/charts/ChartTimeframeControls.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
  src/components-v2/vault-detail/charts/ChartsHeader.tsx
  src/components-v2/vault-detail/charts/VaultChart.tsx
  src/mobx/model/vaults/vault-charts.ts
  src/mobx/stores/InfluenceVaultStore.ts
  src/mobx/stores/VaultChartsStore.ts
  yarn.lock
Labels: enhancement

#2258 feat: update v3 charting support
  package.json
  src/components-v2/InfluenceVault/InfluenceVaultInfoPanel.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
  src/components-v2/vault-detail/charts/VaultChart.tsx
  src/components-v2/vault-detail/specs/VaultMetrics.tsx
  src/components-v2/vault-detail/utils.ts
  src/mobx/stores/VaultChartsStore.ts
  src/tests/unit/vault-detail-utils.test.tsx
  yarn.lock
Labels: enhancement

#2264 fix: update yield display for new api response
  package.json
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/landing/VaultItemApr.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
  src/components-v2/vault-detail/charts/VaultChart.tsx
  src/hooks/useVaultInformation.ts
  src/tests/__snapshots__/Landing.test.tsx.snap
  src/tests/__snapshots__/VaultAdvisory.test.tsx.snap
  src/tests/__snapshots__/VaultDeposit.test.tsx.snap
  src/tests/__snapshots__/VaultWithdraw.test.tsx.snap
  src/tests/sett-details/__snapshots__/Breadcrumbs.test.tsx.snap
  src/tests/sett-details/__snapshots__/Description.test.tsx.snap
  src/tests/sett-details/__snapshots__/Holdings.test.tsx.snap
  src/tests/sett-details/__snapshots__/SpecsCard.test.tsx.snap
  src/tests/utils/samples.ts
  src/tests/vaults/VaultItemApr.test.tsx
  src/tests/vaults/__snapshots__/VaultItemApr.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultMetrics.test.tsx.snap
  src/utils/componentHelpers.ts
  yarn.lock
Labels: enhancement

#2269 staging: tech debt updates
  package.json
  src/components-v2/InfluenceVault/InfluenceVaultInfoPanel.tsx
  src/components-v2/InfluenceVault/InfluenceVaultPerfomanceTab.tsx
  src/components-v2/InfluenceVault/InfluenceVaultUtil.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/common/PercentageSelector.tsx
  src/components-v2/common/StrategyFees.tsx
  src/components-v2/common/VaultFees.tsx
  src/components-v2/common/dialogs/VaultConversionAndFee.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultDialogTitle.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/landing/VaultItemApr.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
  src/components-v2/vault-detail/VaultDetail.tsx
  src/components-v2/vault-detail/charts/BoostChart.tsx
  src/components-v2/vault-detail/charts/ChartTimeframeControls.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
  src/components-v2/vault-detail/charts/ChartsHeader.tsx
  src/components-v2/vault-detail/charts/VaultChart.tsx
  src/components-v2/vault-detail/holdings/Holdings.tsx
  src/components-v2/vault-detail/specs/VaultMetrics.tsx
  src/components-v2/vault-detail/utils.ts
  src/hooks/useVaultInformation.ts
  src/mobx/model/vaults/influence-vault-data.ts
  src/mobx/model/vaults/vault-charts.ts
  src/mobx/stores/InfluenceVaultStore.ts
  src/mobx/stores/TransactionsStore.ts
  src/mobx/stores/VaultChartsStore.ts
  src/tests/__snapshots__/Landing.test.tsx.snap
  src/tests/__snapshots__/VaultAdvisory.test.tsx.snap
  src/tests/__snapshots__/VaultDeposit.test.tsx.snap
  src/tests/__snapshots__/VaultWithdraw.test.tsx.snap
  src/tests/sett-details/__snapshots__/Breadcrumbs.test.tsx.snap
  src/tests/sett-details/__snapshots__/Description.test.tsx.snap
  src/tests/sett-details/__snapshots__/Holdings.test.tsx.snap
  src/tests/sett-details/__snapshots__/SpecsCard.test.tsx.snap
  src/tests/unit/vault-detail-utils.test.tsx
  src/tests/utils/samples.ts
  src/tests/vaults/VaultItemApr.test.tsx
  src/tests/vaults/__snapshots__/VaultItemApr.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
  src/tests/vaults/__snapshots__/VaultMetrics.test.tsx.snap
  src/utils/componentHelpers.ts
  src/utils/useNumericInput.ts
  yarn.lock
Labels: enhancement

#2275 fix: reference vault type for boost
  src/components-v2/VaultListItemTags/index.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultDialogTitle.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
Labels: bug

#2276 fix: vault tag updates
  src/components-v2/VaultListItemTags/index.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultDialogTitle.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
Labels: bug

#2280 fix: update isBoostable check
  src/components-v2/vault-detail/charts/ChartsCard.tsx
Labels: bug

#2281 fix: isBoostable logic update
  src/components-v2/vault-detail/charts/ChartsCard.tsx
Labels: bug

#2277 fix: vault tags display
  src/components-v2/VaultListItemTags/index.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultDialogTitle.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
Labels: bug

#2278 fix: sort apr sources by apr %
  src/components-v2/InfluenceVault/InfluenceVaultPerfomanceTab.tsx
  src/components-v2/VaultApyInformation/index.tsx
Labels: enhancement

#2294 chore: remove projection line for influence charts
  src/components-v2/vault-detail/charts/VaultChart.tsx
Labels: enhancement

#2312 staging: dev promotion
  src/components-v2/InfluenceVault/InfluenceVaultPerfomanceTab.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/ibbtc-vault/IbbtcVaultDepositDialog.tsx
  src/components-v2/landing/NoVaults.tsx
  src/components-v2/navbar/NavbarStats.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
  src/components-v2/vault-detail/charts/VaultChart.tsx
  src/components/Boost/Optimizer.tsx
  src/config/environment.ts
  src/config/networks.config.ts
  src/mobx/stores/UserStore.ts
  src/tests/VaultDeposit.test.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
  src/tests/__snapshots__/VaultDeposit.test.tsx.snap
  src/tests/sett-details/SpecsCard.test.tsx
  src/tests/vaults/VaultMetrics.test.tsx
  src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
Labels: enhancement

#2313 release: my apr changes/sorting/deposit modal + bug fixes
  package.json
  src/components-v2/InfluenceVault/InfluenceVaultPerfomanceTab.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components-v2/ibbtc-vault/IbbtcVaultDepositDialog.tsx
  src/components-v2/landing/NoVaults.tsx
  src/components-v2/navbar/NavbarStats.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
  src/components-v2/vault-detail/charts/VaultChart.tsx
  src/components/Boost/Optimizer.tsx
  src/config/environment.ts
  src/config/networks.config.ts
  src/mobx/stores/UserStore.ts
  src/tests/VaultDeposit.test.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
  src/tests/__snapshots__/VaultDeposit.test.tsx.snap
  src/tests/sett-details/SpecsCard.test.tsx
  src/tests/unit/componentHelpers.test.ts
  src/tests/vaults/VaultMetrics.test.tsx
  src/tests/vaults/__snapshots__/VaultListDisplay.test.tsx.snap
  src/utils/componentHelpers.ts
Labels: bug, enhancement

#2316 fix: utilize stagin
  src/config/environment.ts
Labels: bug

#2306 fix: my apr css changes
  src/components-v2/navbar/NavbarStats.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
Labels: design

#2318 staging: apr fix + my apr css fix
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/navbar/NavbarStats.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
Labels: bug, enhancement

#2319 Revert "fix: utilize stagin"
  src/config/environment.ts
Labels: enhancement

#2320 release: mr apr feature + error handling for apr issue
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/navbar/NavbarStats.tsx
  src/tests/__snapshots__/Navbar.test.tsx.snap
Labels: enhancement

#2332 fix: not using yieldApr for influence vault
  src/components-v2/vault-detail/charts/VaultChart.tsx
Labels: enhancement

#2323 fix: infuence-vault show all fees on deposit
  src/components-v2/InfluenceVault/InfluenceVaultFees.tsx
  src/components-v2/InfluenceVault/InfluenceVaultSpecs.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
Labels: bug, enhancement
