Repository Badger-Finance/v2-ui, pull requests merged in 2022-07, with the labels that each got.

#2176 chore: add new aura vaults
  public/assets/icons/bb-a-dai.svg
  public/assets/icons/bb-a-usdc.svg
  public/assets/icons/bb-a-usdt.svg
  public/assets/img/bond-bcrvibbtc.png
  public/assets/img/bond-bvecvx.png
  public/assets/img/bond-cvx.png
  public/assets/img/bond-wbtc.png
  src/config/deployments/mainnet.json
  src/config/system/strategies.ts
  src/mobx/model/network/eth.network.ts
Labels: enhancement

#2177 chore: temp aura vault advisory update
  .github/workflows/codeql_analysis.yml
  src/components-v2/common/dialogs/AdvisoryLink.tsx
  src/components-v2/common/dialogs/AuraLockingVaultAdivsory.tsx
  src/components-v2/common/dialogs/VaultAdvisory.tsx
  src/mobx/model/network/eth.network.ts
  src/mobx/model/vaults/advisory-type.ts
Labels: enhancement

#2182 release: bvecvx reward frequency descriptor fix
  public/assets/icons/bb-a-dai.svg
  public/assets/icons/bb-a-usdc.svg
  public/assets/icons/bb-a-usdt.svg
  src/components-v2/BveCvxSpecs/index.tsx
Labels: enhancement

#2185 chore: initial deviation from in app network defs
  src/components-v2/TransactionToast/index.tsx
  src/components-v2/VaultDeprecationWarning/index.tsx
  src/components-v2/WalletTransaction/index.tsx
  src/components-v2/common/NetworkGasWidget.tsx
  src/components-v2/common/NetworkNotification.tsx
  src/components-v2/common/NetworkWidget.tsx
  src/components-v2/common/WalletDrawer.tsx
  src/components-v2/common/WalletLiquidityPoolLinks.tsx
  src/components-v2/ibbtc-vault/IbbtcVaultDepositDialog.tsx
  src/components-v2/landing/VaultListDisplay.tsx
  src/components-v2/navbar/NavbarStats.tsx
  src/components-v2/navbar/NavbarTabs.tsx
  src/components-v2/network-selector/NetworkOption.tsx
  src/components-v2/vault-detail/Footer.tsx
  src/components-v2/vault-detail/VaultDetail.tsx
  src/components-v2/vault-detail/holdings/NoHoldings.tsx
  src/components-v2/vault-detail/specs/VaultDetailLinks.tsx
  src/components/IbBTC/index.tsx
  src/config/networks.config.ts
  src/mobx/model/locked-deposits/network-locked-deposits-config.ts
  src/mobx/model/network/arbitrum.network.ts
  src/mobx/model/network/avalanche.network.ts
  src/mobx/model/network/bsc.network.ts
  src/mobx/model/network/chain.ts
  src/mobx/model/network/eth.network.ts
  src/mobx/model/network/ftm.network.ts
  src/mobx/model/network/local.network.ts
  src/mobx/model/network/matic.network.ts
  src/mobx/stores/GasPricesStore.ts
  src/mobx/stores/LockedDepositsStore.ts
  src/mobx/stores/NetworkStore.ts
  src/mobx/stores/RootStore.ts
  src/mobx/stores/TransactionsStore.ts
  src/mobx/stores/TreeStore.ts
  src/mobx/stores/VaultStore.ts
  src/mobx/stores/lockedCvxDelegationStore.ts
  src/tests/Landing.test.tsx
  src/tests/Navbar.test.tsx
  src/tests/NetworkGasWidget.test.tsx
  src/utils/componentHelpers.ts
Labels: enhancement

#2187 feat: utilize vault api auto detection
  package.json
  public/assets/icons/aurabal.svg
  public/assets/icons/bb-a-dai.svg
  public/assets/icons/bb-a-usdc.svg
  public/assets/icons/bb-a-usdt.svg
  public/assets/icons/graviaura.svg
  src/components-v2/ibbtc-vault/IbbtcVaultDepositDialog.tsx
  src/components-v2/vault-detail/holdings/DepositInfo.tsx
  src/components-v2/vault-detail/specs/VaultDetailLinks.tsx
  src/config/deployments/mainnet.json
  src/config/environment.ts
  src/mobx/model/network/chain.ts
  src/mobx/model/network/eth.network.ts
  src/mobx/stores/TreeStore.ts
  src/mobx/stores/VaultStore.ts
  yarn.lock
Labels: enhancement

#2188 chore: add vault order for lp vault
  src/config/deployments/mainnet.json
  src/mobx/model/network/eth.network.ts
Labels: enhancement

#2189 chore: add redeem update balances + tokens tracking
  src/components/IbBTC/Redeem.tsx
  src/mobx/stores/UserStore.ts
Labels: enhancement

#2202 chore: add ninja analytics links
  package.json
  src/components-v2/vault-detail/NewVaultWarning.tsx
  src/components-v2/vault-detail/specs/VaultDetailLinks.tsx
  src/config/system/strategies.ts
  yarn.lock
Labels: enhancement

#2197 Issue 2183 projected yields
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/landing/VaultItemApr.tsx
  src/components-v2/landing/VaultListItem.tsx
  src/components-v2/landing/VaultListItemMobile.tsx
  src/hooks/useVaultInformation.ts
  src/tests/vaults/VaultItemApr.test.tsx
  src/utils/componentHelpers.ts
Labels: enhancement

#2204 feat: generic influence vaults
  src/components-v2/BveCvxBribeChart/index.tsx
  src/components-v2/BveCvxFrequencyInfo/index.tsx
  src/components-v2/BveCvxInfluenceFeesInfo/index.tsx
  src/components-v2/BveCvxWithdrawalInfo/index.tsx
  src/components-v2/InfluenceVault/InfluenceVaultChart.tsx
  src/components-v2/InfluenceVault/InfluenceVaultDetail.tsx
  src/components-v2/InfluenceVault/InfluenceVaultFees.tsx
  src/components-v2/InfluenceVault/InfluenceVaultInfoPanel.tsx
  src/components-v2/InfluenceVault/InfluenceVaultListModal.tsx
  src/components-v2/InfluenceVault/InfluenceVaultModal.tsx
  src/components-v2/InfluenceVault/InfluenceVaultPerfomanceTab.tsx
  src/components-v2/InfluenceVault/InfluenceVaultSpecs.tsx
  src/components-v2/InfluenceVault/InfluenceVaultUtil.tsx
  src/components-v2/InfluenceVault/InfoDialog.tsx
  src/components-v2/VaultDepositedAssets/index.tsx
  src/components-v2/common/MarkupText.tsx
  src/components-v2/vault-detail/VaultDetailWrapper.tsx
  src/components-v2/vault-detail/charts/ChartsCard.tsx
  src/components-v2/vault-detail/specs/Claims.tsx
  src/config/bve-cvx/vote-influence-fees.json
  src/config/routes.tsx
  src/hooks/useVaultInformation.ts
  src/mobx/RootStore.ts
  src/mobx/model/charts/bve-cvx-emission-round.ts
  src/mobx/model/charts/influence-vaults-graph.ts
  src/mobx/model/vaults/influence-vault-data.ts
  src/mobx/stores/InfluenceVaultStore.ts
  src/mobx/stores/VaultStore.ts
  src/mobx/stores/bveCvxInfluenceStore.ts
  src/tests/sett-details/__snapshots__/SpecsCard.test.tsx.snap
Labels: enhancement

#2228 fix: ibbtc minting + value scaling
  package.json
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/common/dialogs/VaultDeposit.tsx
  src/components-v2/common/dialogs/VaultWithdraw.tsx
  src/components/IbBTC/Mint.tsx
  src/config/routes.tsx
  src/mobx/model/tokens/token-balance.ts
  yarn.lock
Labels: bug

#2238 chore: add beta warnings
  src/components-v2/common/BetaAdvisory.tsx
  src/components/App.tsx
  src/mobx/stores/LockedDepositsStore.ts
Labels: enhancement

#2240 chore: mark vaults as new
  src/components-v2/VaultApyBreakdownItem/index.tsx
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/landing/VaultItemApr.tsx
  src/components-v2/landing/VaultLogo.tsx
  src/tests/unit/token/token-balance.test.ts
  src/utils/componentHelpers.ts
  src/utils/enums/boosted-rewards.enum.ts
Labels: enhancement

#2245 chore: update sdk for guest list ussages
  package.json
  yarn.lock
Labels: bug

#2247 chore: handle new calculation + update / add tests
  src/components-v2/VaultApyInformation/index.tsx
  src/components-v2/landing/VaultItemApr.tsx
  src/hooks/useVaultInformation.ts
  src/tests/unit/componentHelpers.test.ts
  src/tests/vaults/__snapshots__/VaultItemApr.test.tsx.snap
  src/utils/componentHelpers.ts
Labels: bug, enhancement
